### ISSUE TITLE
Sample not working

### ISSUE THREAD

**Issue by coccor** [dotnetcore/DotnetSpider#33]
When trying to run `BaseUsage` sample i get an error in `Spider.cs` in `CheckIfSettingsCorrect()` method.

`
if (Site.RemoveOutboundLinks && (Site.Domains == null || Site.Domains.Length == 0))
{	
`
 `   throw new SpiderException($"When you want remove outbound links, the domains should not be null or empty.");
}`

I guess the `Domains` property is required if `RemoveOutboundLinks` is `true`, but I don't know what is the purpose of that property.

**Comment by zlzforever** [comment]
1. My bad, i didn't update my sample codes after refactorying. You are right, if you want to remove outbound links, should set `Domains` and `RemoveOutboundLinks` in `Site`. When you want to crawl www.a.com, and there are some outbound links like www.b.com/... in it, you may want to remove/exclude all links which are not belonging to www.a.com.   Previouslly, I got `Domains` from Request/StartUrls, but it's not a good way in my opinion, since there may be more than one outbound domains and you only want to remove one of them.
2. DotnetSpider is very flexible, if you don't wanna use the `RemoveOutboundLinks` feature built in, you  can also implement an `AfterDownloadCompleteHandler` to customize the html before DotnetSpider processing it.
Hope helpfull, Excuse my broken English.
